[project]
name = "progetto-se2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.0.1",
    "polars>=1.27.1",
    "streamlit>=1.44.1",
]
